{
  "type": "record",
  "name": "BetAccepted",
  "namespace": "com.sportsbook.events",
  "fields": [
    {
      "name": "betId",
      "type": "string"
    },
    {
      "name": "playerId",
      "type": "string"
    },
    {
      "name": "marketId",
      "type": "string"
    },
    {
      "name": "maxPayout",
      "type": "double"
    },
    {
      "name": "Stake",
      "type": "double"
    },
    {
      "name": "liabilityAfter",
      "type": "double"
    },
    {
      "name": "odds",
      "type": "double"
    },
    {
      "name": "timestamp",
      "type": "long"
    }


  ]
}