spring:
  application:
    name: payment-ingress-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

psv:
  topics:
    deposit-ingest: deposit-ingest
